version: '3.6'

services:
  db-pgsql:
    image: postgres:latest
    hostname: pgsql
    volumes:
      - ./db-pgsql:/var/lib/postgresql/data
      - ./db-archive:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=db_jenkins
      - POSTGRES_USER=jenkins
      - POSTGRES_PASSWORD=jenkins
      - POSTGRES_INITDB_ARGS='--data-checksums'
      - PGDATA='/var/lib/postgresql/data/pgdata'
    networks:
      - jenkins-net
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
      placement: 
        constraints: [node.role == manager]

  adminer:
    image: adminer:latest
    hostname: adminer
    environment:
      - ADMINER_DESIGN=lucas-sandery
    ports:
      - '9030:8080'
    networks:
      - jenkins-net
    depends_on:
      - db-pgsql
    deploy:
      restart_policy:
        condition: on-failure
      placement: 
        constraints: [node.role == manager]

  app:
    image: gworkx/python:jenkins
    hostname: python
    volumes:
     - ./app-code:/app
    environment:
     - DB_HOST=db-pgsql
     - DB_NAME=POSTGRES_DB
     - DB_PASSWORD=POSTGRES_PASSWORD
    entrypoint: /app/app.py
    ports:
      - '5030:8000'
    networks:
      - jenkins-net
    depends_on:
      - db-pgsql
    deploy:
      restart_policy:
        condition: on-failure
      placement: 
        constraints: [node.role == manager]

networks:
  jenkins-net:
    driver: overlay
